package br.com.eder.cms.model;

/**
 * ItemTopico generated by hbm2java
 */
public class ItemTopico  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idItemTopico;
	private Topicos topicos;
    private String nome;
    private String descricao;
    private String status;

    public ItemTopico() {
    }
    
    
    public ItemTopico(Integer id) {
    	this.setIdItemTopico(id);
    }
   
	private int hashCode = Integer.MIN_VALUE;


	public Integer getIdItemTopico() {
		return idItemTopico;
	}


	public void setIdItemTopico(Integer idItemTopico) {
		this.idItemTopico = idItemTopico;
	}


	public String getNome() {
		return nome;
	}


	public void setNome(String nome) {
		this.nome = nome;
	}


	public String getDescricao() {
		return descricao;
	}


	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


		public boolean equals (Object obj) {
			if (null == obj) return false;
			if (!(obj instanceof ItemTopico)) return false;
			else {
				ItemTopico castOther = (ItemTopico) obj;
				if (null == this.getIdItemTopico() || null == castOther.getIdItemTopico()) return false;
				else return (this.getIdItemTopico()).equals(castOther.getIdItemTopico());
			}
		}
	
		public int hashCode () {
			if (Integer.MIN_VALUE == this.hashCode) {
				if (null == this.getIdItemTopico()) return super.hashCode();
				else {
					String hashStr = this.getClass().getName() + ":" + this.getIdItemTopico().hashCode();
					this.hashCode = hashStr.hashCode();
				}
			}
			return this.hashCode;
		}


		public void setTopicos(Topicos topicos) {
			this.topicos = topicos;
		}


		public Topicos getTopicos() {
			return topicos;
		}

}


