package br.com.eder.cms.model;

/**
 * Secao generated by hbm2java
 */
public class Secao  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSecao;
    private String nome;
    private String status;

    public Secao() {
    }
    
    
    public Secao(Integer id) {
    	this.setIdSecao(id);
    }
   
	private int hashCode = Integer.MIN_VALUE;


 	public Integer getIdSecao() {
		return idSecao;
	}


	public void setIdSecao(Integer idSecao) {
		this.idSecao = idSecao;
	}


	public String getNome() {
		return nome;
	}


	public void setNome(String nome) {
		this.nome = nome;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


		public boolean equals (Object obj) {
			if (null == obj) return false;
			if (!(obj instanceof Secao)) return false;
			else {
				Secao castOther = (Secao) obj;
				if (null == this.getIdSecao() || null == castOther.getIdSecao()) return false;
				else return (this.getIdSecao().equals(castOther.getIdSecao()));
			}
		}
	
		public int hashCode () {
			if (Integer.MIN_VALUE == this.hashCode) {
				if (null == this.getIdSecao()) return super.hashCode();
				else {
					String hashStr = this.getClass().getName() + ":" + this.getIdSecao().hashCode();
					this.hashCode = hashStr.hashCode();
				}
			}
			return this.hashCode;
		}

}


