package br.com.eder.cms.model;

/**
 * Topicos generated by hbm2java
 */
public class Topicos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTopicos;
    private Secao secao;
    private String nome;
    private String detalhe;
    private String status;

    public Topicos() {
    }
    
    
    public Topicos(Integer id) {
    	this.setIdTopicos(id);
    }
   
	private int hashCode = Integer.MIN_VALUE;

 	public Integer getIdTopicos() {
		return idTopicos;
	}


	public void setIdTopicos(Integer idTopicos) {
		this.idTopicos = idTopicos;
	}


	public Secao getSecao() {
		return secao;
	}


	public void setSecao(Secao secao) {
		this.secao = secao;
	}


	public String getNome() {
		return nome;
	}


	public void setNome(String nome) {
		this.nome = nome;
	}


	public String getDetalhe() {
		return detalhe;
	}


	public void setDetalhe(String detalhe) {
		this.detalhe = detalhe;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


		public boolean equals (Object obj) {
			if (null == obj) return false;
			if (!(obj instanceof Topicos)) return false;
			else {
				Topicos castOther = (Topicos) obj;
				if (null == this.getIdTopicos() || null == castOther.getIdTopicos()) return false;
				else return (this.getIdTopicos().equals(castOther.getIdTopicos()));
			}
		}
	
		public int hashCode () {
			if (Integer.MIN_VALUE == this.hashCode) {
				if (null == this.getIdTopicos()) return super.hashCode();
				else {
					String hashStr = this.getClass().getName() + ":" + this.getIdTopicos().hashCode();
					this.hashCode = hashStr.hashCode();
				}
			}
			return this.hashCode;
		}
}


