package br.com.eder.cms.model;


/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String usuario;
     private String senha;
     private String email;

    public Usuario() {
    }
    
    
    public Usuario(String id) {
    	this.setUsuario(id);
    }
   
	private int hashCode = Integer.MIN_VALUE;

    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
		this.hashCode = Integer.MIN_VALUE;
    }
    
       
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
		this.hashCode = Integer.MIN_VALUE;
    }
    
       
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
		this.hashCode = Integer.MIN_VALUE;
    }
    
       


	 	public boolean equals (Object obj) {
			if (null == obj) return false;
			if (!(obj instanceof Usuario)) return false;
			else {
				Usuario castOther = (Usuario) obj;
				if (null == this.getUsuario() || null == castOther.getUsuario()) return false;
				else return (this.getUsuario().equals(castOther.getUsuario()));
			}
		}
	
		public int hashCode () {
			if (Integer.MIN_VALUE == this.hashCode) {
				if (null == this.getUsuario()) return super.hashCode();
				else {
					String hashStr = this.getClass().getName() + ":" + this.getUsuario().hashCode();
					this.hashCode = hashStr.hashCode();
				}
			}
			return this.hashCode;
		}
		
}


